### ISSUE TITLE
add LICENSE

### ISSUE THREAD

**Issue by Vinzent03** [ianhi/jupyterlab_vim-system-clipboard-support#6]
I would like to use this script for [obsidian](https://obsidian.md) as a plugin. Is this ok and could you add a license?

**Comment by ianhi** [comment]
Hi @Vinzent03 thanks for bring this up and for asking. I just added one in https://github.com/ianhi/jupyterlab_vim-system-clipboard-support/commit/9b3e70a62c9595b6fea395effb85396c87ea0e16

feel free to use this in obisidian (which looks very nice). A few notes:
1. If you have the motivation then a better solution would be to upstream these fixes to codemirror directly. I just haven't had the time.
2. I imagine you're using electron for obsidian. If this is the case then it will probably be worth your while to implement paste as well. I haven't done this due to firefox's restrictions on `readText` and that it's a more involved function to replicate. But the former issue will not be relevant when using electron.
   - If you do implement this and want to contribute it here then I'm tracking paste over at https://github.com/ianhi/jupyterlab_vim-system-clipboard-support/issues/2
3. Of the two jlab-vim extensions I've made I think this one is the more useful. However, the more popular one by far implements a vimrc. You may also be interested in checking out how that one works https://github.com/ianhi/jupyterlab-vimrc

**Comment by Vinzent03** [comment]
Sorry for the late answer, but thank you for the response. I am really not familiar with Codemirror, so wont be able to implement a better solution.
